name: Java Maven Backend Tests
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'AllergenScanner/backend/AllergenScanner/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: AllergenScanner/backend/AllergenScanner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven and run JUnit tests
      run: mvn -B test
      
    - name: Upload JUnit test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: junit-test-reports
        path: AllergenScanner/backend/AllergenScanner/target/surefire-reports/
        retention-days: 7
